stages:
  data_load: 
    cmd: python -c "import kagglehub; kagglehub.dataset_download(handle='jajidhasan/mental-health', output_dir='data/raw')"
    outs:
      - data/raw/mental_health.csv

  train:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/raw/mental_health.csv
    outs:
      - data/processed/features.csv